[[plugins]]
repo = 'Shougo/vinarise'
on_cmd = 'Vinarise'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'stephpy/vim-php-cs-fixer'
on_ft = 'php'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'zchee/deoplete-go'
build= 'make'
if   = '''has('python3')'''
on_ft = 'go'
hook_add = '''
let g:deoplete#sources#go#gocode_binary = '~/go/bin/gocode'
'''


[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
if   = '''has('python3')'''
on_ft = 'rust'
hook_add = '''
let g:deoplete#sources#rust#racer_binary = '/home/cookies/.cargo/bin/racer'
let g:deoplete#sources#rust#rust_source_path = '/home/cookies/.vim/rust/rust/src'
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp']
hook_add = '''
let g:deoplete#sources#clang#libclang_path = '/usr/lib/libclang.so'
let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
'''

[[plugins]]
repo = 'vim-syntastic/syntastic'
on_ft = ['php']
hook_add = '''
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_enable_signs = 1
let g:syntastic_echo_current_error = 1
let g:syntastic_auto_loc_list = 2
let g:syntastic_enable_highlighting = 1
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_mode_map = {
            \ 'mode': 'active',
            \ 'active_filetypes': ['php']
            \}
let g:syntastic_php_checkers = ['phpcs']
let g:syntastic_php_phpcs_args = '--standard=psr2'

let g:syntastic_ocaml_checkers = [g:opamshare . '/bin/ocamlmerlin']
'''
