[[plugins]]
repo = 'Shougo/vinarise'
on_cmd = 'Vinarise'

[[plugins]]
repo = 'airblade/vim-rooter'
on_cmd = ['Rooter', 'RooterToggle']
hook_add = '''
let g:rooter_change_directory_for_non_project_files = 'current'
let g:rooter_manual_only = 1
let g:rooter_cd_cmd="lcd"
'''

[[plugins]]
repo = 'Shougo/deoplete-clangx'
on_ft = 'cpp'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'
hook_add = '''
autocmd FileType vue syntax sync fromstart
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = 'cpp'

# repo = 'vim-scripts/sh.vim--Cla'
# repo = 'stephpy/vim-php-cs-fixer'
# repo = 'deoplete-plugins/deoplete-go'
# repo = 'nvie/vim-flake8'
# repo = 'vim-syntastic/syntastic'
# repo = 'hashivim/vim-terraform'
