[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build= 'make'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neco-syntax'
[[plugins]]
repo = 'Shougo/neoinclude.vim'
[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'airblade/vim-rooter'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'cookie-s/project.vim'
[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
let g:EasyMotion_keys='hjklasdfHJKLASDFgyurtGYURTopqweOPQWEnmzxcvbNMZXCVB'
let g:EasyMotion_leader_key=";"
let g:EasyMotion_grouping=1
hi EasyMotionTarget ctermbg=black ctermfg=red
hi EasyMotionShade  ctermbg=black ctermfg=blue
'''

[[plugins]]
repo = 'vim-scripts/matchit.zip'
[[plugins]]
repo = 'slim-template/vim-slim'
[[plugins]]
repo = 'embear/vim-localvimrc'

[[plugins]]
repo = 'AndrewRadev/switch.vim'
[[plugins]]
repo = 'tpope/vim-endwise'
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'shiracamus/vim-syntax-x86-objdump-d'
[[plugins]]
repo = 'osyo-manga/vim-brightest'
[[plugins]]
repo = 'cookie-s/vim-unite-disas'

[[plugins]]
repo = 'majutsushi/tagbar'
[[plugins]]
repo = 'alpaca-tc/alpaca_tags'
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_post_update = ':UpdateRemotePlugins'
hook_source = '''
let g:deoplete#enable_at_startup = 1
'''
[[plugins]]
repo = 'roxma/nvim-yarp'
if   = '''! has('nvim')'''
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if   = '''! has('nvim')'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
if   = '''has('python3')'''
build = 'sh install.sh'

[[plugins]]
repo = 'Shougo/denite.nvim'
[[plugins]]
repo = 'ujihisa/unite-colorscheme'
[[plugins]]
repo = 'Shougo/echodoc.vim'

[[plugins]]
repo = 'jvirtanen/vim-octave'

[[plugins]]
repo = 'kevinw/pyflakes-vim'
[[plugins]]
repo = 'nvie/vim-flake8'

