name: nvim

on:
  push:
  schedule:
  - cron: '23 5 * * *' # 5:23 daily

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 1

      - uses: thinca/action-setup-vim@v1 # https://github.com/thinca/action-setup-vim
        id: vim
        with:
          download: always
          vim_type: neovim
          vim_version: stable

      # - name: ln .vimrc
      #   run: |
      #     ln -s $GITHUB_WORKSPACE/.vimrc ~

      # - run: |
      #     ${{ steps.vim.outputs.executable }} --version

      # - run: |
      #     ${{ steps.vim.outputs.executable }} -c q

